### ISSUE TITLE
When the login screen is appear then navigation menu should not appear 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#806] opened 2021-03-25 05:45 UTC

**Comment by rashmi0301** [comment] 2021-05-01 12:59
any update ?
this is still occur

**Comment by rashmi0301** [comment] 2021-05-08 11:08
![Screenshot (44)](https://user-images.githubusercontent.com/79301742/117536965-f2f34200-afb2-11eb-89af-d6d2a537ae67.png)

this issue still occur but occur sometimes . 
this is the technical issue so developer can do this .

**Comment by AmitojSingh1** [comment] 2021-05-14 23:26
Duplicate of #588

**Closed as completed by AmitojSingh1** 2021-05-14 23:26 UTC
Labels: cloud-app, dev-app
